AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack for monitoring resources

Parameters:
  SecurityAlertsTopicARN:
    Description: The ARN of the Security Alerts SNS topic
    Type: String
  CloudPlatformTeamAlertsTopicARN:
    Description: The ARN of the Cloud Platforms SNS topic
    Type: String

Resources:
  ApacheAcccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
         LogGroupName: "ApacheAccessLog"

  LowSeverityMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: ApacheAccessLog
      FilterPattern: "%severity=low%"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "ApacheAccessLogs"
          MetricName: "IKKomEraanLowSeverity"
    DependsOn: ApacheAcccessLogGroup

  HighSeverityMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: ApacheAccessLog
      FilterPattern: "%severity=high%"
      MetricTransformations:
        - MetricValue: "1"
          MetricNamespace: "ApacheAccessLogs"
          MetricName: "IKKomEraanHighSeverity"
    DependsOn: ApacheAcccessLogGroup

  LowSeverityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: low severity found
      AlarmDescription: |-
        # Attention !!
        A low severity action has been recorded
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - !Ref SecurityAlertsTopicARN
      InsufficientDataActions: []
      MetricName: IKKomEraanLowSeverity
      Namespace: ApacheAccessLogs
      Statistic: Sum
      Dimensions: []
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing

  HighSeverityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Red Alert
      AlarmDescription: |-
        # !! RED ALERT !! RED ALERT !!
        Intrusion Detected!
      ActionsEnabled: true
      OKActions: []
      AlarmActions:
        - !Ref SecurityAlertsTopicARN
        - !Ref CloudPlatformTeamAlertsTopicARN- arn:aws:sns:eu-west-1:862753365563:Opdracht-2-SecurityStack-NP8EWS9BKHU4-CloudPlatformTeamAlertsTopic-1VEVsZwCiT1k
      InsufficientDataActions: []
      MetricName: IKKomEraanHighSeverity
      Namespace: ApacheAccessLogs
      Statistic: Sum
      Dimensions: []
      Period: 300
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: missing